- job-template:
    name: 'ops-config-yaml-check-{platform}'
    node: openswitch
    wrappers:
        - build-timeout:
            timeout: 120
    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: '{platform}'
    publishers:
        - post-ws-clean

- job:
    name: 'ops-config-yaml-gate-as5712'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 180

    builders:
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: 'as5712'
    publishers:
        - post-ws-clean

- job:
    name: 'ops-config-yaml-gate-genericx86-64'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 180

    builders:
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'
        - check-docker-state
        - clear-test-logs
        - module-test:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'
        - capture-test-logs

    publishers:
        - conditional-gather-test-results
        - conditional-htmlreports
        - archive-syslog
        - archive-test-logs-on-failure
        - post-ws-clean

- job-group:
    name: 'ops-config-yaml-jobs'
    jobs:
      - 'ops-config-yaml-check-{platform}'
